services:
  db:
    image: postgres
    container_name: challenge_hetmo
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: challenge_hetmo_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./migrations:/app/migrations
    # Ensure the db is ready before starting the app
    command: [ "./wait-for-it.sh", "db:5432", "--", "./main" ]

volumes:
  postgres_data:
